### ISSUE TITLE
🧹 [Updates]: Organize the folder with scripts.

### ISSUE THREAD

**Issue by shurco** [werbot/werbot#160]

**Comment by JoseAngel1196** [comment]
Hi, I would like to contribute to this project, can you provide more details on exactly what you mean by organizing the folder with scripts? @shurco

**Comment by shurco** [comment]
> Hi, I would like to contribute to this project, can you provide more details on exactly what you mean by organizing the folder with scripts? @shurco

Hi, thank you for your interest in the project!
I am already working on this task. I planned to optimize part of the scripts and reformat the structure.
